/**
 * This module was automatically generated by `ts-interface-builder`
 */
import * as t from "ts-interface-checker";
// tslint:disable:object-literal-key-quotes

export const Format = t.union(t.lit("COMIC"), t.lit("SHOW"), t.lit("BOOK"));

export const Session = t.iface([], {
  saga: t.opt("number"),
  act: "number",
  createdAtMs: "number",
});

export const SeriesItem = t.iface([], {
  title: "string",
  sessions: t.array("Session"),
  createdAtMs: "number",
  updatedAtMs: "number",
  archived: "boolean",
  complete: "boolean",
  favorite: "boolean",
  format: "Format",
  viewUrl: t.opt("string"),
});

export const Collection = t.iface([], {
  id: "string",
  name: t.opt("string"),
  seriesItems: t.array("SeriesItem"),
  compactView: "boolean",
  updatedAtMs: "number",
});

const exportedTypeSuite: t.ITypeSuite = {
  Format,
  Session,
  SeriesItem,
  Collection,
};
export default exportedTypeSuite;
